apiVersion: skaffold/v2beta2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: profile
    context: .
deploy:
  helm:
    releases:
    - name: profile
      chartPath: profile-chart
      skipBuildDependencies: true
      values:
        image: profile
