apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-configmap
data:
  DBHOST: {{ include "postgresql.fullname" . }}
  DBUSER: {{ .Values.postgresql.postgresqlUsername}}
  DBPASS: {{ .Values.postgresql.postgresqlPassword }}
  DBNAME: {{ .Values.postgresql.postgresqlDatabase }}

