apiVersion: skaffold/v2beta2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: notif
    context: .
deploy:
  helm:
    releases:
    - name: notif
      chartPath: notif-chart
      skipBuildDependencies: true
      values:
        image: notif

