replicaCount: 1

fullnameOverride: "orders"

image: "orders:0.2.14"

service:
  type: NodePort
  port: 9000

postgresql:
  enabled: true
  postgresqlUsername: ordersuser
  postgresqlPassword: orderspasswd
  postgresqlDatabase: ordersdb
  persistence:
    size: 0.1Gi
  service:
    port: "5432"
